version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    ports:
      - '5434:5432'
    volumes: 
      - users-db:/var/lib/postgresql/data
volumes:
  users-db:
    driver: local